# Generated by Django 5.2 on 2025-05-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(default="Guest", max_length=24)),
                ("hp", models.PositiveIntegerField(default=800)),
                ("speed", models.FloatField(default=220)),
                ("damage", models.PositiveIntegerField(default=40)),
                ("fire_rate", models.FloatField(default=2.0)),
                ("x", models.FloatField(default=0)),
                ("y", models.FloatField(default=0)),
                ("angle", models.FloatField(default=0)),
                ("gold", models.PositiveIntegerField(default=0)),
                ("xp", models.PositiveIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="game.gamesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("damage", "Damage x2 (6s)"),
                            ("velocity", "Speed +40% (6s)"),
                            ("vanish", "Invisible (4s)"),
                            ("regen", "Fast regen (6s)"),
                            ("xp", "+1 XP"),
                        ],
                        max_length=10,
                    ),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("spawned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orbs",
                        to="game.gamesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat",
                    models.CharField(
                        choices=[
                            ("hp", "HP"),
                            ("speed", "Speed"),
                            ("damage", "Gun Damage"),
                            ("fire_rate", "Fire Rate"),
                        ],
                        max_length=12,
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1)),
                ("bought_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="game.car",
                    ),
                ),
            ],
        ),
    ]
